### ISSUE TITLE
Fails on GUI start

### ISSUE THREAD

**Issue by vahldiek** [PublicExperimentDatabase/PublicExperimentGUI#1]
Hi,

I followed the installation guide and tried to start the GUI, but it fails. Do you assume a certain node version? Having a tested Dockerfile might be best. Coupled with a github action to check that the Dockerfile builds and successfully starts the GUI.

```
npm run dev 

> next-gui@0.1.0 dev /mnt/c/Users/avahldie/OneDrive - Intel Corporation/service/SoR23/PublicExperimentGUI
> next dev

/mnt/c/Users/avahldie/OneDrive - Intel Corporation/service/SoR23/PublicExperimentGUI/node_modules/next/dist/cli/next-dev.js:362
            showAll: args["--show-all"] ?? false,
                                         ^

SyntaxError: Unexpected token ?
    at Module._compile (internal/modules/cjs/loader.js:723:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.dev (/mnt/c/Users/avahldie/OneDrive - Intel Corporation/service/SoR23/PublicExperimentGUI/node_modules/next/dist/lib/commands.js:10:30)
    at Object.<anonymous> (/mnt/c/Users/avahldie/OneDrive - Intel Corporation/service/SoR23/PublicExperimentGUI/node_modules/next/dist/bin/next:141:28)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! next-gui@0.1.0 dev: `next dev`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the next-gui@0.1.0 dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/vahldiek/.npm/_logs/2023-07-17T14_52_43_993Z-debug.log
```

npm log:
```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'run', 'dev' ]
2 info using npm@6.14.4
3 info using node@v10.19.0
4 verbose run-script [ 'predev', 'dev', 'postdev' ]
5 info lifecycle next-gui@0.1.0~predev: next-gui@0.1.0
6 info lifecycle next-gui@0.1.0~dev: next-gui@0.1.0
7 verbose lifecycle next-gui@0.1.0~dev: unsafe-perm in lifecycle true
8 verbose lifecycle next-gui@0.1.0~dev: PATH: /usr/share/npm/node_modules/npm-lifecycle/node-gyp-bin:/mnt/c/Users/avahldie/OneDrive - Intel Corporation/service/SoR23/PublicExperimentGUI/node_modules/.bin:/home/vahldiek/.local/bin:/home/vahldiek/bin:/home/vahldiek/.vscode-server/bin/660393deaaa6d1996740ff4880f1bad43768c814/bin/remote-cli:/home/vahldiek/.cargo/bin:/home/vahldiek/.local/bin:/home/vahldiek/bin:/home/vahldiek/.local/bin:/home/vahldiek/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/usr/lib/wsl/lib:/mnt/c/Program Files/Eclipse Adoptium/jdk-17.0.7.7-hotspot/bin:/mnt/c/WINDOWS/system32:/mnt/c/WINDOWS:/mnt/c/WINDOWS/System32/Wbem:/mnt/c/WINDOWS/System32/WindowsPowerShell/v1.0/:/mnt/c/WINDOWS/System32/OpenSSH/:/mnt/c/Users/avahldie/AppData/Local/Microsoft/WindowsApps:/mnt/c/Users/avahldie/AppData/Local/Programs/Microsoft VS Code/bin:/snap/bin:/home/linuxbrew/.linuxbrew/bin/:/home/linuxbrew/.linuxbrew/bin/:.:/home/linuxbrew/.linuxbrew/bin/:.
9 verbose lifecycle next-gui@0.1.0~dev: CWD: /mnt/c/Users/avahldie/OneDrive - Intel Corporation/service/SoR23/PublicExperimentGUI
10 silly lifecycle next-gui@0.1.0~dev: Args: [ '-c', 'next dev' ]
11 silly lifecycle next-gui@0.1.0~dev: Returned: code: 1  signal: null
12 info lifecycle next-gui@0.1.0~dev: Failed to exec dev script
13 verbose stack Error: next-gui@0.1.0 dev: `next dev`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/share/npm/node_modules/npm-lifecycle/index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:198:13)
13 verbose stack     at ChildProcess.<anonymous> (/usr/share/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:198:13)
13 verbose stack     at maybeClose (internal/child_process.js:982:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
14 verbose pkgid next-gui@0.1.0
15 verbose cwd /mnt/c/Users/avahldie/OneDrive - Intel Corporation/service/SoR23/PublicExperimentGUI
16 verbose Linux 5.10.102.1-microsoft-standard-WSL2
17 verbose argv "/usr/bin/node" "/usr/bin/npm" "run" "dev"
18 verbose node v10.19.0
19 verbose npm  v6.14.4
20 error code ELIFECYCLE
21 error errno 1
22 error next-gui@0.1.0 dev: `next dev`
22 error Exit status 1
23 error Failed at the next-gui@0.1.0 dev script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

Thanks,
Anjo

**Comment by zjyhhhhh** [comment]
The version of node I'm using is v18.12.1.
I think you can fix it by trying to upgrade the version of node or deleting the `next.config.js` file, then running `npm run dev`.
I will add Dockerfile soon.

**Comment by vahldiek** [comment]
Dockerfile (in docker): 
```
FROM node:18

RUN apt-get update && \
    apt-get upgrade

RUN mkdir /src

WORKDIR /src

COPY . .

RUN npm install || yarn install

RUN echo "MONGODB_URI=localhost\nLocal_Path=\n" > .env.local

EXPOSE 3000

ENTRYPOINT ["npm"]
```

Building via ```docker build -t pegui -f Dockerfile ../```.

Seems to work for me for now by running ```docker run --rm pegui run dev```. 

My only issue seems to be my local network config to connect to the server, but this is something I need to figure out.

**Comment by zjyhhhhh** [comment]
OK thanks. i will push this dockerfile

**Comment by vahldiek** [comment]
Expose in the dockerfile doesn't seem to be sufficient in my setup: ``` docker run --rm -p 127.0.0.1:3000:3000 pegui run dev```
